extraEnv:
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: aws-dns-creds
      key: AWS_ACCESS_KEY
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: aws-dns-creds
      key: AWS_SECRET_ACCESS_KEY
provider: aws
domainFilters:
- amitdsouza.io
txtOwnderId: external-dns.odysseycloud.io