apiVersion: v2
name: external-dns-aws
namespace: dns-infra
description: external-dns-aws Helm chart for Kubernetes
type: application
version: 5.4.5
appVersion: "0.9.0"

dependencies:
- name: external-dns
  chart: bitnami/external-dns
  version: 5.4.5
  repository: https://charts.bitnami.com/bitnami
  values:
    - ../common-external-dns-values.yaml
