apiVersion: v2
name: nginx-ingress
namespace: kube-infra
description: nginx-ingress Helm chart for Kubernetes
type: application
version: 3.34.0
appVersion: "0.47.0"

dependencies:
- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 3.34.0
  repository: https://kubernetes.github.io/ingress-nginx
  values:
    - ../common-ingress-nginx-values.yaml