apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-infra-setup
  namespace: argo
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: git@github.com:odysseycloud/kubernetes.git
          revision: HEAD
          directories:
          - path: k8s-infra/argo/*
          - exclude: true
            path: k8s-infra/argo/argo-workflows
          - path: k8s-infra/dns-infra/*
          - path: k8s-infra/security/*
      - list:
          elements:
          - cluster: demo
            url: https://34.105.124.251
            values:
              CLIENT_ENVIRONMENT: demo             
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: odysseycloud
      source:
        repoURL: git@github.com:odysseycloud/kubernetes.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            # - 'common-{{path.basename}}-values.yaml'
            - '{{cluster}}-{{path.basename}}-values.yaml'
      destination:
        server: https://34.105.124.251
        # namespace: '{{ path.basename }}'
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
            prune: true 
            selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true         
