apiVersion: v2
name: cert-manager
namespace: dns-infra
description: cert-manager Helm chart for Kubernetes
type: application
version: 1.4.0
appVersion: "1.4.0"

dependencies:
- name: cert-manager
  chart: jetstack/cert-manager
  version: 1.4.0
  repository: https://charts.jetstack.io
  values:
    - common-cert-manager-values.yaml