apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo
  finalizers:
  - resources-finalizer.argo.argoproj.io
spec:
  project: odysseycloud
  source:
    path: kube-infra/argo/argo-workflows
    repoURL: git@github.com:odysseycloud/kubernetes.git
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://34.105.124.251
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true 
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true       