repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

values:
  - sealed-secrets:
      enabled: true
      
environments:
  demo:
    values:
      - sealed-secrets:
          enabled: true

releases:
  - name: sealed-secrets-controller
    namespace: secrets
    chart: sealed-secrets/sealed-secrets
    version: 1.16.1
    condition: sealed-secrets.enabled


