repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

values:
  - argo-cd:
      enabled: true 
      
environments:
  demo:
    values:
      - argo-cd:
          enabled: true


releases:
  - name: argo-cd
    namespace: argo
    chart: argo/argo-cd
    version: 3.13.1
    condition: argo-cd.enabled
    values:
      - ../kube-infra/argo/argo-cd/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-argo-cd-values.yaml

  - name: argocd-applicationset
    namespace: argo
    chart: argo/argocd-applicationset
    version: 1.3.0
    condition: argo-cd.enabled 
    values:
      - ../kube-infra/argo/argocd-applicationset/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-argocd-applicationset-values.yaml
    # hooks:
    #   - events: ["prepare"]
    #     command: "kubectl"
    #     args: ["apply", "--validate=true", "--filename=values/common/argocd-applicationset-crds.yaml"]



  - name: cert-manager
    namespace: kube-infra
    chart: jetstack/cert-manager
    version: 1.4.0
    values:
      - ../kube-infra/kube-infra/cert-manager/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-cert-manager-values.yaml


  - name: external-dns-aws
    namespace: kube-infra
    chart: bitnami/external-dns
    version: 5.4.5
    values:
      - ../kube-infra/kube-infra/external-dns-aws/common-external-dns-aws-values.yaml
      - ../kube-infra/kube-infra/external-dns-aws/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-external-dns-aws-values.yaml       