apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-dns-creds
  namespace: dns-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgDKGUPnpazSLvJtgJ/eVa3HG3EiQ3DPIKqEtDi+vUK4pgVh1J82yU/DU4E2/NHvN+b7aB8kZO5jcMR1MLFv0ysX0LJKCAO0eRJ5ZnO+59BZSxhseSuFGYXRFunbeSrzccfdWN4DNQJ83N0VjaB215EENvf1uOqLVo1xe54BXVdl1uISDsKKCeIWR+m26/9eHzpdiVlM1qHEX37RC+FJGClpCcJ3c8JWu/q5vUgiiCEKu7hxz3sc/ce875erZkf/7fSatZngv5Dp9Yp750pVRCtvLXZZdy3H4Do3OE51QgEtSb6c7nwUv53oAu7RLUjSEQGdcVL6iXYp2zlKNdNjIWBYUbl21LVj6t7enc+Wt3uJNdGeiiz8DAr8o+WYeOasm/sQnkkBJBSkvDvLYPnbzCyB7+HCa1XiWmxTv5iidJO8hci+3eqHgN6yBWGdXXN1CT7FdeYDj15kN49nZ9HPlyG8vy0ZSlb5EwDSOWK3tsWZH32rJlpj7h6SgUt7kCw/4NBOLih4ALyJRX6RYAZKs8EXMTqUU80rE7gyH2rPMVKJ4aUrinZhdVUz4dsp/qg8PolqTBcMrGR7hrsNa6r9y1OJvPJ7bSSlFgARnB8OGJvY0nL/H8Ycie6S3qTP/qpNwvTaUbpm//oMLVVYMkWEnLeoPF/GngsafSI/et43US4N+7EWX1jFnKOniu9hQv1vnO5LON21S1QegoXoJnba8fFPVR4MJQ==
    AWS_SECRET_ACCESS_KEY: AgBvKXfS4jST+lGXVeDPAPPuyX/xmtJ7/QsZeA7cjHK/Y5M2oTC4MMNQ5u8ApZ5Rt3VwuDpvGXa5/uql8v+VMoGrPXL3t4PCiNwCAlHY2/AayMUMUCJX9bFEszgFkcff8notQQHOZLYfyftYdjeAyt3Xn5aK7qfNw86igqHvXl3Ulhko5r1vAo2jlNbI/CCBp4/36QXzoF8BEdtpGg4ZvCrB+FPxxqDjm96HqhBBHuQ/uMfWHBpkOneey+MtxWW44Gsc+xGDVmZuByBReqdpBzxQkVUOeGv+W3f48bjtQ9MRhnpcfGtyDx94zkImw2J63oRJCnPYQpKlFh6V9kdVeVPiftyoiDwnJ/Z5ocZ5Wk6HT8DRmwZjpyGIJFaFZJuxZ0tt8gkR9ryx/0zOftUyjHwyqmWiFmTYXGyQnY58Gl6r2LBER6TG6t8p4BDgAOHNV9rgrNcUfi2JncpDt8b4JeuyQ1KvtrYu99esyN/ItFGZSLNXZxt+/xid+wqDL+jiT8GihLq5ETBbqN/HAxSwmnqv8vCZKY140zRqhOG04M3qDqilFUcwNLpFhAGGObAdgLv41kse/8bYsn2YozM7ezWwdGUYCPOkTwkzLcgsSBypelZO24UKwvZvsW5c/t+3ZsiJmxvvICcjrLmXmXVzUjZnanwnKObJjLm9vIQ6wlcPfYn19ThthJqHwI43N7k/ra5Q7N0j+LVFbKYTONZSBN4s2Pn1cCQXJtdD+ifrkDXubUiU5w7MGzAO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-dns-creds
      namespace: dns-infra
    type: Opaque

