apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-dns-creds
  namespace: kube-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgCZzddtVFWjB2hlnm0KjkeNODvXLCeqTeWxjHrSrEBLqUNytRCdBEQBwoBuArZ71//Kb6W4kqdS8e5HrTXlTMDPU1bh2XgoQbVpSzk13qt7O8Ea/heaFziALpXngqJt0AVTjKT7YyRK2cj83gv4BelvOECvjhwE12lGihanhLiJRxXWxCVh8HEKrqo/1DZw86QmCwwZpqRJXqoToL/UHOAkzS0qax4x6x77lr+HhNIfRm99QlFt+9oBMePdIcuIo5Y/wwn8EBjd3ArBFpsc4MTF1gVqwUEzONRpPUwW+EVaPW7iMLbgSEABHrR89Nka+h95Z7zqb6Upm8637Wuw6rQ03u6CsFBgGTS252AGD3YHp8c65pTu7h8925g84J+vucWBRONXexnF6HlWrj1D6zbPj5eHgty8aqFNdeW7mkmGzforXgkPuUoAUkzc790zk+fVIIdDvtCrqq1mu1Zd9IxmXBY9OXqoV0SZPYBZXp49a06voNNe2rBrCRC3dyAjFVY2YwbB5r9HRJkDMmytYkUBC6Vpy/PLSEkX6nUFnrzaXMdASY9WHyx5RLE1d22wrk7bKF5X5TR1kMrgK52w/QKI5pBhOT0hFQrKU7sK3wgiNXBW7F89ZWRSEFMQ/PvIkxfBkZR9VAiUDsqPXmFHpsxbLe4NGCk7W+xc4tMzXyIAnNqBh97IWNDj50JA/NFB6UtHw/2dqfojSbz25ZxqKckEJUGt4g==
    AWS_SECRET_ACCESS_KEY: AgCtzbEPvYjI/lLiehbqYlN+ZuMj6GX9oQogb11S9/qGB190WanLaU2WSIc+j0e4836SbjX/pRGEhV5nd7Qked0jU21REMsE7MLCvggg9ZQ7RDWmJpm6W4eCVEqicRpiSge2F3+A/9qeCqGdS5c8OLYtmRTFLmvFqesfmDYm4SMMlV7VAL0w1hdkdkABrm8Z7fgAdNfzviN+efcEOv1JDCSHJ20fQGr8fkrcFsiEi1IHyKbXAHzUkUVPOkR6iGckDYSDTsOei7vK4+tJrj43ANlg1AYXktzSToQimOai+pCEdHyleAhR8GD5TI93gV4bWbJRgV1yAGAIVkxYnhTaNYFHwmtS/RAw2skOwSIsj66ueW0gLZQWxuhXWnROb/MjcwQP8tgz/XNst9yydhGCEeEJFbfjyjD9uDODSHqAXlZnOYk6aw2VNoHu5L8jToLgfGVP6r4thCcc0bjxCnR//jtmpQMq1q7flfzgLUnbxoOZYLEDKXzguy6ZlIGdUDrnTeSJbr2Hxf/blaXYKVXfWkz6sexOTGkdYRtjmm+tXmHC2zQGVHdPkO7ieVKfHXKi/ml297JrjiTQ45FDnHkvdleVP9JtM+7oo8LrB/Jf8yqXPWxZ0+V/V8sU9UR/0tgqWM1oaLsaLmnLknCBdh+HxLyG7n3KGJsFDoFAP0RQi/wySxdo0S3VSX03JN6Qv24w8q3yqbe4az1FJ7YQZGOR183xDdysQOtTMXL5u+S3lgWqR8/xxKyP2edn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-dns-creds
      namespace: kube-infra
    type: Opaque

